name: Scheduled Api Scrape

on:
  schedule:
    - cron: '*/30 * * * *'   # Runs every 30 minutes (hopefully)
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Download executable
        run: |
          curl -L -o backend https://github.com/Paficent/Roblox-Api-Tracker-Backend/releases/latest/download/backend
          chmod +x backend
          
      - name: Run executable
        run: ./backend
        
      - name: Remove script artifacts
        run: |
          rm backend

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "API Updated"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Send notification to Discord # You need to create a Repository secret called DISCORD_WEBHOOK_URL for this to work
      #   run: |
      #     curl -H "Content-Type: application/json" \
      #          -d '{"content": "Scheduled API Scrape workflow has run successfully."}' \
      #          ${{ secrets.DISCORD_WEBHOOK_URL }}
